name: Merge API changelogs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge-api-changelogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch
        run: |
          BRANCH_NAME="update-changelog-$(date +%s)"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Run merge-api-changelogs
        run: ./merge-api-changelogs

      - name: Push changes (created by merge-api-changelogs)
        run: |
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Update API changelog" --body "This PR updates the API changelog." --base main --head $BRANCH_NAME

      - name: Auto-merge PR (Optional)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --state open --head $BRANCH_NAME --json number --jq '.[0].number')
          gh pr merge $PR_NUMBER --merge
