name: Merge API changelogs

on:
  push:
    branches: [main]

jobs:
  merge-api-changelogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run merge-api-changelogs
        id: run_merge
        run: |
          ./merge-api-changelogs
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Fail job if changelog merge failed
        if: ${{ steps.run_merge.outputs.exit_code != '0' }}
        run: exit 1

      - name: Report status to CZO
        if: ${{ steps.run_merge.outputs.exit_code != '0' && github.repository == 'zulip/zulip' && github.event_name == 'push' }}
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: "jmyTglDWKl8BCWapOt9FXfx41La6yXrp"
          email: "bot-bot@xyzkeshi.zulipchat.com"
          organization-url: "https://xyzkeshi.zulipchat.com/"
          to: "core team"
          topic: "general chat"
          type: "stream"
          content: "Failed"

