name: Merge API changelogs

on:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:

jobs:
  merge-api-changelogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add execute permissions to merge-api-changelogs
        run: chmod +x ./merge-api-changelogs

      - name: Run merge-api-changelogs
        run: ./merge-api-changelogs

      - name: Push changes
        run: git push origin HEAD:main