name: Merge API changelogs

on:
  push:
    branches: [main]

jobs:
  check-feature-level-updated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Add required permissions
        run: chmod +x ./check-feature-level-updated

      - name: Run tools/check-feature-level-updated
        id: run_check
        run: ./check-feature-level-updated >> $GITHUB_OUTPUT

      - name: Report status to CZO
        if: steps.run_check.outputs.fail == 'true'
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: "jmyTglDWKl8BCWapOt9FXfx41La6yXrp"
          email: "bot-bot@xyzkeshi.zulipchat.com"
          organization-url: "https://xyzkeshi.zulipchat.com/"
          to: "core team"
          topic: ${{ steps.run_check.outputs.topic }}
          type: "stream"
          content: ${{ steps.run_check.outputs.content }}

